defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Dataset related
sampling_rate: 16000
segment: 32000

batch_size: 4
batch_size_valid: 1
epochs: 200

eval_every: 100  # compute test metrics every so epochs

# Loss related
loss:
  l1_loss:
    weight: 1
  multispectral_loss:
    weight_lmag: 0.5
    weight_conv: 0.5
    weight_comp: 0
    weight_pha: 0.5
    fft_sizes: [1024, 2048, 512]
    hop_sizes: [120, 240, 50]
    win_lengths: [600, 1200, 240]
    compress_factor: 0.3
  metricgan_loss:
    weight_disc: 10
    weight_gen: 1
    ndf: 16
    fft_size: 400
    hop_size: 100
    win_length: 400
    compress_factor: 0.3
    pesq_workers: 8
    use_torch_pesq: false

# Optimization related
lr: 5e-4
lr_decay: 0.99
optim: adamW
betas: [0.8, 0.99]
clip_grad_norm: 
validate_with_pesq: false

# Logging and printing, and does not impact training
device: cuda
num_prints: 10
num_workers: 5
ddp:
  master_addr: localhost
  master_port: 12355

checkpoint: true
checkpoint_file: checkpoint.th
continue_from:
samples_dir: samples
log_dir: tensorbd

# Other stuff
seed: 2039

# Hydra config
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}

  job:
    chdir: true

  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr