defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Dataset related
sampling_rate: 16000
segment: 64000
stride: 16000

shift: 8000
shift_same: false
remix: true
bandmask: 0.2
revecho: 0

batch_size: 4
batch_size_valid: 1
epochs: 10

eval_every: 10  # compute test metrics every so epochs

# Loss related
loss:
  l1_loss:
    weight: 0.2
  # multispectral_loss:
  #   weight_mag: 0.9
  #   weight_com: 0.2
  #   weight_pha: 0.3
  #   fft_sizes: [800, 400, 200]
  #   hop_sizes: [200, 100, 50]
  #   win_lengths: [800, 400, 200]
  spectral_loss:
    weight_mag: 0.9
    weight_com: 0.2
    weight_pha: 0.3
    compress_factor: 0.3
    fft_size: 400
    hop_size: 100
    win_length: 400
  # metricgan_loss:
  #   weight_disc: 1.0
  #   weight_gen: 0.1
  #   ndf: 16
  #   fft_size: 400
  #   hop_size: 100
  #   win_length: 400
  #   compress_factor: 0.3


# Optimization related
lr: 3e-4
optim: adamW
betas: [0.9, 0.99]
clip_grad_norm: 

# Logging and printing, and does not impact training
device: cuda
num_prints: 10
num_workers: 5
ddp:
  master_addr: localhost
  master_port: 12355

checkpoint: true
checkpoint_file: checkpoint.th
continue_from: 
samples_dir: samples
log_dir: tensorbd

# Other stuff
seed: 2039

# Hydra config
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}

  job:
    chdir: true

  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr