defaults:
  - _self_
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Dataset related
segment: 32000
n_fft: 400
hop_size: 100
win_size: 400
compress_factor: 0.3
use_pcs400: true


use_huggingface: false
input_train_file_list: VoiceBank+DEMAND/training_list.txt
input_valid_file_list: VoiceBank+DEMAND/test_list.txt
batch_size: 2
batch_size_valid: 1
epochs: 200

# Optimization related
lr: 5e-4
lr_decay: 0.99
optim: adamW
betas: [0.8, 0.99]

# Logging and printing, and does not impact training
device: cuda
num_workers: 1
ddp:
  master_addr: localhost
  master_port: 12355

log_interval: 500
summary_interval: 500
validation_interval: 1000
evaluation_interval: 50
best_models_num: 5

continue_from: 
samples_dir: samples
log_dir: tensorbd
save_code: true

# Other stuff
seed: 2039

# Hydra config
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d_%H-%M-%S}

  job:
    chdir: true

  job_logging:
    handlers:
      file:
        class: logging.FileHandler
        mode: w
        formatter: colorlog
        filename: trainer.log
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stderr